title: Catherine Wilfred
logo: docs/assets/github.jpg
description: Result driven data analyst skilled in data visualization, statistical analysis and communication. Proficient in Excel, SQL, PowerBI and Python.
#show_downloads: true
theme: jekyll-theme-minimal
